baseURL = "https://blog.muxin.io/"
theme = "hugo-PaperMod"
defaultContentLanguage = "zh"

[minify]
    disableXML = true
    minifyOutput = true

[params]
    defaultTheme = "auto"
    disableThemeToggle = false
    disableSpecial1stPost = false
    ShowReadingTime = true

[languages]
    [languages.zh]
        languageName = "Chinese"
        title = "方牧心的博客"
        [languages.zh.params]
            description = "这都被你给发现了"
            author = "方牧心"
        [languages.zh.params.label]
            text = "轻语慕心"
            icon = "/apple-touch-icon.png"
            iconHeight = 35
        [[languages.zh.menu.main]]
            identifier = "home"
            name = "首页"
            url = "https://muxin.io/"
            weight = -2
        [[languages.zh.menu.main]]
            identifier = "blog"
            name = "博客"
            url = "/"
            weight = -1
        [[languages.zh.menu.main]]
            identifier = "about"
            name = "关于我"
            url = "https://muxin.io/about/"
    [languages.en]
        languageName = "English"
        title = "Muxin Fang's Blog"
        [languages.en.params]
            description = "You found something"
            author = "Muxin Fang"
        [languages.en.params.label]
            text = "Whisper from Heart"
            icon = "/apple-touch-icon.png"
            iconHeight = 35
        [[languages.en.menu.main]]
            identifier = "home"
            name = "Home"
            url = "https://muxin.io/en/"
            weight = -2
        [[languages.en.menu.main]]
            identifier = "blog"
            name = "Blog"
            url = "/"
            weight = -1
        [[languages.en.menu.main]]
            identifier = "about"
            name = "About Me"
            url = "https://muxin.io/en/about/"